### ISSUE TITLE
Text modality (GloVe features)

### ISSUE THREAD

**Issue by dori2063** [smartcameras/SelfCrossAttn#1]
Hi, Vandana, 
Thank you for sharing your work with code.

Could you share the GloVe features ('*_text.npy', not '*_nlp_trans.npy') or detail which is the pre-trained GloVe word vectors for that?

**Comment by vandana-rajan** [comment]
Hi,

I have used the feature files given in the repo - https://github.com/david-yoon/attentive-modality-hopping-for-SER.

So, if you request and get the processed IEMOCAP dataset, you can see the text features in '/processed_Yoon/IEMOCAP/seven_category_120/folds/fold01/train_text.npy' .

Hope this helps.

**Comment by dori2063** [comment]
'*_text.npy' is not exist in that repo. 
I just wrote a code to make the '*_text.npy' file and got a similar accuracy in your paper. 
Thank you!

**Comment by vandana-rajan** [comment]
Ah. yes. you are correct. I had created the '_text.npy' using both the 'W_embedding.npy' and '_nlp_trans.npy' files.

Did these experiments a year ago and my memory got a bit rusty :) 

I will add the small snippet of code I used to create the '_text.npy' .
