### ISSUE TITLE
_text.np

### ISSUE THREAD

**Issue by deeplearning00** [smartcameras/SelfCrossAttn#2]
Hi, Vandana,
Thank you for sharing your work with code.

Could you share the GloVe features ('_text.npy', not '_nlp_trans.npy') or detail which is the pre-trained GloVe word vectors for that?

**Comment by vandana-rajan** [comment]
Hi,

I have used the feature files given in the repo  - https://github.com/david-yoon/attentive-modality-hopping-for-SER. 

So, if you request and get the processed IEMOCAP dataset, you can see the text features in '/processed_Yoon/IEMOCAP/seven_category_120/folds/fold01/train_text.npy' . 

Hope this helps.

**Comment by vandana-rajan** [comment]
Hi,

I found that the original repo from Dr. Yoon doesn't contain the '_text.npy' files.

I have uploaded a new script 'pre_process_text_data.py' to generate the '_text.npy' files.
